version: '3.9'
services:
  user-service:
    build: .
    ports:
      - 8000:3000
    volumes:
      - ./user-service:/app
    depends_on:
      - db
  user-service-db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: KuantoKusta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.dbdata:/var/lib/mysql
    ports:
      - 53066:3306