version: '3.9'
services:
  user-service:
    build: ./user-service
    ports:
      - 8000:3000
    volumes:
      - ./user-service:/app
    depends_on:
      - user-service-db
  user-service-db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: kk_users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./user-service/.dbdata:/var/lib/mysql
    ports:
      - 53066:3306
  product-service:
    build: ./product-service
    ports:
      - 8010:3000
    volumes:
      - ./product-service:/app
    depends_on:
      - product-service-db
  product-service-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kuantokusta
      - MONGO_INITDB_ROOT_PASSWORD=kuantokusta
      - MONGO_INITDB_DATABASE=kk_products
    volumes:
      - ./product-service/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./product-service/.dbdata:/data/db